import {PrioridadeAction} from './MethodGet.ts/prioridade';
import {SetorAction} from './MethodGet.ts/setor';
import {StatusAction} from './MethodGet.ts/status';
import {DetalhamentoOrdemAction} from '../actions/MethodPost.ts/detalhamentoordem';
import {LancamentosAction} from './MethodPost.ts/lancamentos';
import {LogandoAction} from './MethodPost.ts/logando';
import {NovaOrdemAction} from './MethodPost.ts/novaordem';
import {NovoUserAction} from './MethodPost.ts/novouser';
import {OrdemServicoAction} from './MethodPost.ts/ordemservico';
import {SolicitaPecasAction} from './MethodPost.ts/solicitapecas';
import {TokenAction} from './MethodPost.ts/token';
import {VerificaAction} from './MethodPost.ts/verifica';
import {VerificaManutencaoAction} from './MethodPost.ts/verificamanutencao';
import {VerificaServicoAction} from './MethodPost.ts/verificaservico';
import {alteraStatusOsAction} from './MethodPatch.ts/alterastatusos';
import {ManutencaoAction} from './MethodGet.ts/manutencao';
import {MaquinaAction} from './MethodGet.ts/maquina';
import {SelecionaVerificacaoAction} from './MethodGet.ts/selecionaverificacao';
import {AutenticacaoAction} from './MethodPost.ts/autenticacao';
import {AvaliacaoAction} from  './MethodPost.ts/avaliacao';
import {PegaMinhasOsAction} from './MethodPost.ts/pegaminhasos';
import {RegistroOperacoesAction} from './MethodPost.ts/registrooperacoes';
import { EpiAction } from './MethodPost.ts/epi';
import { EpiCompletoAction } from './MethodPost.ts/epicompleto';


export {PrioridadeAction};
export {SetorAction};
export {StatusAction};
export {DetalhamentoOrdemAction};
export {LancamentosAction};
export {LogandoAction};
export {NovaOrdemAction};
export {NovoUserAction};
export {OrdemServicoAction};
export {SolicitaPecasAction};
export {TokenAction};
export {VerificaAction};
export {VerificaManutencaoAction};
export {VerificaServicoAction};
export {alteraStatusOsAction};
export {ManutencaoAction};
export {MaquinaAction};
export {SelecionaVerificacaoAction};
export {AutenticacaoAction};
export {AvaliacaoAction};
export {PegaMinhasOsAction};
export {RegistroOperacoesAction};
export { EpiAction };
export {EpiCompletoAction};
